# +------------------------------------------------------+ #
# |            Default Config File ( MST-Battle )        | #
# +------------------------------------------------------+ #
############################################################